
 
pipeline {
    agent {
        label 'worker_node'
    }

    stages{
 
        stage("build and push"){
            steps{
                script{

            docker.withRegistry('', 'docker_credentials') {
            def customImage = docker.build("shashwatpp/ruby-budgetapp-a1:${env.BUILD_ID}","./docker_app_data/")

            customImage.push()
                }
            }

            }
        }
        stage("deploy"){
            steps{
                
                script{
                def filespath = "/home/root/jenkins_workspace/workspace/budgy_app/docker_app_data"
                sh "cd ${filespath} && chmod +x deploy.sh  && echo IMGVERSION=${env.BUILD_ID} >> .env && ./deploy.sh"

                }
            
            }
        }
    }
}

