apiVersion: v1
kind: Service
metadata:
  name: budgetapp-service
spec:
  type: NodePort
  selector:
    app: budgetapp
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 3000
      # nodePort: 30036