version: "3.9"

networks:
  test:
    name: test
    driver: bridge

services:

  loki:
    image: grafana/loki:2.6.0
    ports:
      - "3100:3100"
    networks:
      - test

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      # - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promconfig.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - test

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - test

  db:
    image: postgres:14.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: shash
      POSTGRES_PASSWORD: pathak
      POSTGRES_DB: budgy_app
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./shash-postgres:/var/lib/postgresql/data

    networks:
      - test
    depends_on:
      - loki

  Budgy:
    image: shashwatpp/ruby-budgetapp-a1:${IMGVERSION}
    ports:
      - '1234:3000'
    volumes:
        - ./:/myapp
    env_file:
      - .env
    depends_on:
      - db
      - loki

    networks:
      - test

volumes:
  shash-postgres:
  budgy: